### ISSUE TITLE
Number format exceptions

### ISSUE THREAD

**Issue by marceloaqno** [mycontroller-org/mycontroller#134]
Hi,
several of these messages appear in mycontroller log file after one of the my nodes sent an invalid sensor value (nan, -nan, inf):
```
2016-01-25 14:02:52,441 ERROR [Thread-3] [org.mycontroller.standalone.mysensors.MessageMonitorThread:73] RawMessage[NodeId:9,ChildSensorId:1,MessageType:1,Ack:0,SubType:38,Payload:-nan] throws exception while processing!, 
java.lang.NumberFormatException: For input string: "-nan"
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source) ~[na:1.8.0_71]
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source) ~[na:1.8.0_71]
	at java.lang.Double.parseDouble(Unknown Source) ~[na:1.8.0_71]
	at java.lang.Double.valueOf(Unknown Source) ~[na:1.8.0_71]
	at org.mycontroller.standalone.NumericUtils.getDouble(NumericUtils.java:48) ~[mycontroller-standalone-0.0.2-alpha6-single.jar:na]
	at org.mycontroller.standalone.mysensors.ProcessRawMessage.recordSetTypeData(ProcessRawMessage.java:588) ~[mycontroller-standalone-0.0.2-alpha6-single.jar:na]
	at org.mycontroller.standalone.mysensors.ProcessRawMessage.messageTypeSelector(ProcessRawMessage.java:95) ~[mycontroller-standalone-0.0.2-alpha6-single.jar:na]
	at org.mycontroller.standalone.mysensors.MessageMonitorThread.processRawMessage(MessageMonitorThread.java:61) [mycontroller-standalone-0.0.2-alpha6-single.jar:na]
	at org.mycontroller.standalone.mysensors.MessageMonitorThread.run(MessageMonitorThread.java:87) [mycontroller-standalone-0.0.2-alpha6-single.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_71]
```
I also noticed some missing information about the node in the Action Board (webgui) after that.

**Comment by jkandasa** [comment]
@marceloaqno I hope your sensor sends `V_VOLTAGE` value. It should be a double value. MyController tries to convert `-nan` to Double value and failed. I believe this error won't effect your node details.

What exact information missing on action board?

**Comment by marceloaqno** [comment]
@jkandasa yes, V_VOLTAGE values (it's a S_MULTIMETER type). Node 9 has 13 sensors, but only 7 of them are showing.

**Comment by jkandasa** [comment]
@marceloaqno can you send me the complete mycontroller.log? It might give some clue to narrow down this issue.

**Comment by marceloaqno** [comment]
@jkandasa sure, https://drive.google.com/file/d/0B_-1ZYkXkahacGMxS0lxcTI0Q3M/view?usp=sharing

**Comment by jkandasa** [comment]
@marceloaqno Hi it looks like you are using alpha5 version of database with alpha6 version. There is schema changes in alpha6 version, It won't support for previous version of database. You have to start from fresh.

**Comment by marceloaqno** [comment]
@jkandasa I did that (delete the file mycontroller.h2.db) after upgrading to alpha6.
Once I saw those lines on the log:
```
org.h2.jdbc.JdbcSQLException: Column "reachable" not found [42122-176]
```
I thought starting from scratch would be the case, I just kept the logs.

**Comment by jkandasa** [comment]
@marceloaqno did you note the time stamp of the log? Is it new log?

**Comment by jkandasa** [comment]
This expected issue(`Number format exceptions`) if we send unreadable measurement data.
