### ISSUE TITLE
issue alpha7 compilation

### ISSUE THREAD

**Issue by Mickaelh51** [mycontroller-org/mycontroller#135]
Hi,
I have an issue when I want compile alpha7 (last git clone).

Do you have 0.0.2-alpha7 Release with pre-compiled sources ?

thanks in advance

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project mycontroller-standalone: Compilation failure
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
	at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:516)
	at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:114)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
```

**Comment by jkandasa** [comment]
@Mickaelh51  0.0.2-alpha7 is not yet ready to release. Currently it's in  0.0.2-alpha7-SNAPSHOT version.

can you please elaborate more about the command that you executed?

JDK 1.8 is required.
To get compiled image you have to run 
```
git clone https://github.com/mycontroller-org/mycontroller.git
cd mycontroller
mvn package
```

**Comment by Mickaelh51** [comment]
Thanks,
It's exactly this process what I executed. I'm using jdk 1.8.

Do you want another informations ?

**Comment by jkandasa** [comment]
@Mickaelh51 can you paste complete log on somewhere like http://fpaste.org/ ?

**Comment by Mickaelh51** [comment]
Hi,
thanks for your help ;)
pastbin: http://fpaste.org/315054/38425271/
password: toto5108

++

**Comment by jkandasa** [comment]
@Mickaelh51 Thank you for the log file, seems there is an issue with `lombok`. I tried on another machine but unable to reproduce this issue my side. seems like you are in different platform.
I'm with fedora 23 with JDK 1.8 and works good.
Can you give your platform information?

**Comment by jkandasa** [comment]
@Mickaelh51 until identify the issue you can try this compiled version, update available till commit #422

http://s000.tinyupload.com/?file_id=01619064561924017217

**Comment by Mickaelh51** [comment]
Hi, thanks a lot !

the configuration has changed between alpha6 and 7 ? 
There is no these options:
```
mcc.gateway.type=mqtt
cc.gateway.mqtt.broker.host=tcp://*.*.*.*:1883
mcc.gateway.mqtt.client.id=mc-gateway
mcc.gateway.mqtt.user=gateway
mcc.gateway.mqtt.password=gateway
mcc.gateway.mqtt.topic.publish=mygateway1-in
mcc.gateway.mqtt.topic.subscribe=mygateway1-out
```
I have this isse in log (but I want work with mqqt):
```
KEEPALIVE!: true
2016-01-27 20:27:16,735 ERROR [main] [org.mycontroller.standalone.gateway.serialport.SerialPortjSerialCommImpl:74] Unable to open serial port:[/dev/ttyUSB0]
```
And another issue in web interface:
This issue is present in alpha6 too.
![screenshot-172 16 13 153 8443 2016-01-27 20-27-41](https://cloud.githubusercontent.com/assets/9885404/12625640/f9d307a4-c534-11e5-8bd7-a7ca29ce0e0c.png)


Thanks in advance and I'm sorry to waste your time :(

**Comment by jkandasa** [comment]
@Mickaelh51 It's not a problem in opensource world everyone's contribution is very important.

First I want to tell for now(alpha releases) version to version database upgrade will not support(huge schema changes happening every time). We have to start each version from fresh installation.

So we have to start as brand new for 0.0.2-alpha7 version.

In 0.0.2-alpha7, we made huge changes in back-end and front end. You can configure multiple gateways same time, that too from GUI. Hence I removed CLI configuration settings.

If you are planing to use 0.0.2-alpha7 in production environment, kindly hold on some time, we will release 0.0.2-alpha7 with known issue fixes by Feb-2016 if everything goes well.

**Comment by jkandasa** [comment]
when moving alpha5 to alpha6 clear your browser cache, GUI will get work good.

**Comment by jkandasa** [comment]
kindly reopen this issue if you face with latest development branch
