### ISSUE TITLE
Bug: Grouped sensors graph js error

### ISSUE THREAD

**Issue by manusovich** [mycontroller-org/mycontroller#161]
1. I am creating new grouped sensors chart. Choosing 2 temp sensors. They both are displayed fine on two separate graphs
2. Grouped sensors char is not displayed because of JS error. 

**Error** 
`TypeError: Cannot read property 'length' of undefined
    at SVGGElement.<anonymous> (nv.d3.js:5712)
    at d3.min.js:3
    at H (d3.min.js:1)
    at Array.ka.each (d3.min.js:3)
    at SVGGElement.<anonymous> (nv.d3.js:5710)
    at d3.min.js:3
    at H (d3.min.js:1)
    at Array.ka.each (d3.min.js:3)
    at Array.b (nv.d3.js:5556)
    at Array.ka.call (d3.min.js:3)`

**Data**
/mc/rest/metrics/metricsData?chartType=lineChart&timestampFrom=1457758273944&variableId=50&variableId=53

`[ {
  "unit" : "°C",
  "timeFormat" : "hh:mm:ss a",
  "chartType" : "lineChart",
  "chartInterpolate" : "linear",
  "chartData" : [ {
    "values" : [ [ 1457758285424, 22.9 ], [ 1457758405424, 22.9 ], [ 1457758465424, 22.9 ], [ 1457758525424, 22.8 ], [ 1457758585424, 22.8 ], [ 1457758645424, 22.9 ], [ 1457758765424, 22.8 ], [ 1457758885424, 22.8 ], [ 1457758945424, 22.8 ], [ 1457759005424, 22.8 ], [ 1457759125424, 22.8 ], [ 1457759185424, 22.8 ], [ 1457759305424, 22.8 ], [ 1457759365424, 22.8 ], [ 1457759425424, 22.8 ], [ 1457759485424, 22.8 ], [ 1457759545424, 22.8 ], [ 1457759665424, 22.8 ], [ 1457759725424, 22.8 ], [ 1457759845424, 22.8 ], [ 1457759905424, 22.8 ], [ 1457759965424, 22.8 ], [ 1457760025424, 22.8 ], [ 1457760145424, 22.8 ], [ 1457760205424, 22.7 ], [ 1457760265424, 22.8 ], [ 1457760325424, 22.8 ], [ 1457760445424, 22.8 ], [ 1457760565424, 22.8 ], [ 1457760625424, 22.7 ], [ 1457760685424, 22.7 ], [ 1457760745424, 22.8 ], [ 1457760805424, 22.7 ], [ 1457760865424, 22.7 ], [ 1457760925424, 22.8 ], [ 1457760985424, 22.7 ], [ 1457761105424, 22.7 ], [ 1457761165424, 22.7 ], [ 1457761285424, 22.7 ], [ 1457761345424, 22.7 ], [ 1457761405424, 22.7 ], [ 1457761465424, 22.7 ], [ 1457761525424, 22.7 ], [ 1457761585424, 22.7 ], [ 1457761645424, 22.7 ], [ 1457761765424, 22.7 ] ]
  }, {
    "values" : [ [ 1457758705424, 19.3 ], [ 1457759185424, 19.3 ], [ 1457759545424, 19.2 ], [ 1457759905424, 19.2 ], [ 1457759965424, 19.2 ], [ 1457760205424, 19.1 ], [ 1457760265424, 19.1 ], [ 1457761105424, 19.3 ], [ 1457761165424, 19.2 ], [ 1457761225424, 19.2 ], [ 1457761285424, 19.1 ] ]
  } ]
} ]`

**Screenshot**
<img width="1805" alt="screen shot 2016-03-11 at 11 48 06 pm" src="https://cloud.githubusercontent.com/assets/2063812/13721212/87e0116e-e7e4-11e5-940e-712c42d4c938.png">

**JFYI**: Of of these sensors (id = 50) getting this data for single chart (values for whole day). And graph is displayed on the page:
`[ {
  "id" : 50,
  "variableType" : "Temperature",
  "unit" : "°C",
  "dataType" : "Double",
  "timeFormat" : "hh:mm:ss a",
  "resourceName" : "[G]:rpi2 >> [N]:1:null >> [S]:1:null >> [SV]:Temperature",
  "chartType" : "lineChart",
  "chartInterpolate" : "linear",
  "chartData" : [ {
    "key" : "Average",
    "values" : [ [ 1457676025424, 21.7 ], [ 1457676325424, 21.7 ], [ 1457676625424, 21.7 ], [ 1457676925424, 21.7 ], [ 1457677225424, 21.725 ], [ 1457677525424, 21.8 ], [ 1457677825424, 21.8 ], [ 1457678125424, 21.8 ], [ 1457678425424, 21.8 ], [ 1457678725424, 21.8 ], [ 1457679025424, 21.8 ], [ 1457679325424, 21.8 ], [ 1457679625424, 21.833 ], [ 1457679925424, 21.8 ], [ 1457680225424, 21.85 ], [ 1457680525424, 21.825 ], [ 1457680825424, 21.867 ], [ 1457681125424, 21.82 ], [ 1457681425424, 21.867 ], [ 1457681725424, 21.85 ], [ 1457682025424, 21.875 ], [ 1457682325424, 21.85 ], [ 1457682625424, 21.86 ], [ 1457682925424, 21.833 ], [ 1457683225424, 21.85 ], [ 1457683525424, 21.84 ], [ 1457683825424, 21.85 ], [ 1457684125424, 21.82 ], [ 1457684425424, 21.8 ], [ 1457684725424, 21.8 ], [ 1457685025424, 21.8 ], [ 1457685325424, 21.8 ], [ 1457685625424, 21.8 ], [ 1457685925424, 21.8 ], [ 1457686225424, 21.8 ], [ 1457686525424, 21.8 ], [ 1457686825424, 21.8 ], [ 1457687125424, 21.8 ], [ 1457687425424, 21.8 ], [ 1457687725424, 21.8 ], [ 1457688025424, 21.8 ], [ 1457688325424, 21.8 ], [ 1457688625424, 21.8 ], [ 1457688925424, 21.8 ], [ 1457689225424, 21.8 ], [ 1457689525424, 21.8 ], [ 1457689825424, 21.8 ], [ 1457690125424, 21.8 ], [ 1457690425424, 21.8 ], [ 1457690725424, 21.8 ], [ 1457691025424, 21.8 ], [ 1457691325424, 21.775 ], [ 1457691625424, 21.767 ], [ 1457691925424, 21.767 ], [ 1457692225424, 21.8 ], [ 1457692525424, 21.733 ], [ 1457692825424, 21.8 ], [ 1457693125424, 21.767 ], [ 1457693425424, 21.8 ], [ 1457693725424, 21.767 ], [ 1457694025424, 21.8 ], [ 1457694325424, 21.8 ], [ 1457694625424, 21.8 ], [ 1457694925424, 21.75 ], [ 1457695225424, 21.8 ], [ 1457695525424, 21.8 ], [ 1457695825424, 21.733 ], [ 1457696125424, 21.7 ], [ 1457696425424, 21.8 ], [ 1457696725424, 21.8 ], [ 1457697025424, 21.86 ], [ 1457697325424, 21.8 ], [ 1457697625424, 21.8 ], [ 1457697925424, 21.8 ], [ 1457698225424, 21.8 ], [ 1457698525424, 21.8 ], [ 1457698825424, 21.8 ], [ 1457699125424, 21.8 ], [ 1457699425424, 21.8 ], [ 1457699725424, 21.8 ], [ 1457700025424, 21.8 ], [ 1457700325424, 21.8 ], [ 1457700625424, 21.8 ], [ 1457700925424, 21.8 ], [ 1457701225424, 21.8 ], [ 1457701525424, 21.8 ], [ 1457701825424, 21.8 ], [ 1457702125424, 21.8 ], [ 1457702425424, 21.8 ], [ 1457702725424, 21.8 ], [ 1457703025424, 21.8 ], [ 1457703325424, 21.8 ], [ 1457703625424, 21.8 ], [ 1457703925424, 21.8 ], [ 1457704225424, 21.8 ], [ 1457704525424, 21.8 ], [ 1457704825424, 21.8 ], [ 1457705125424, 21.8 ], [ 1457705425424, 21.8 ], [ 1457705725424, 21.8 ], [ 1457706025424, 21.833 ], [ 1457706325424, 21.875 ], [ 1457706625424, 21.85 ], [ 1457706925424, 21.867 ], [ 1457707225424, 21.9 ], [ 1457707525424, 21.875 ], [ 1457707825424, 21.9 ], [ 1457708125424, 21.9 ], [ 1457708425424, 21.9 ], [ 1457708725424, 21.9 ], [ 1457709025424, 21.9 ], [ 1457709325424, 21.9 ], [ 1457709625424, 21.9 ], [ 1457709925424, 21.9 ], [ 1457710225424, 21.925 ], [ 1457710525424, 21.98 ], [ 1457710825424, 22.0 ], [ 1457711125424, 22.0 ], [ 1457711425424, 22.0 ], [ 1457711725424, 22.0 ], [ 1457712025424, 22.0 ], [ 1457712325424, 22.0 ], [ 1457712925424, 22.0 ], [ 1457713525424, 22.0 ], [ 1457714125424, 22.0 ], [ 1457714425424, 22.0 ], [ 1457714725424, 22.0 ], [ 1457715925424, 22.1 ], [ 1457717125424, 22.15 ], [ 1457717425424, 22.2 ], [ 1457718025424, 22.2 ], [ 1457719225424, 22.2 ], [ 1457719525424, 22.3 ], [ 1457722525424, 22.5 ], [ 1457722825424, 22.55 ], [ 1457723125424, 22.6 ], [ 1457723425424, 22.6 ], [ 1457723725424, 22.6 ], [ 1457724025424, 22.6 ], [ 1457724325424, 22.7 ], [ 1457724625424, 22.7 ], [ 1457724925424, 22.7 ], [ 1457725225424, 22.7 ], [ 1457725525424, 22.7 ], [ 1457725825424, 22.8 ], [ 1457726125424, 22.8 ], [ 1457726425424, 22.8 ], [ 1457726725424, 22.8 ], [ 1457727025424, 22.825 ], [ 1457727325424, 22.875 ], [ 1457727625424, 22.9 ], [ 1457727925424, 22.9 ], [ 1457728225424, 22.9 ], [ 1457728525424, 22.9 ], [ 1457728825424, 22.92 ], [ 1457729125424, 22.975 ], [ 1457729425424, 23.0 ], [ 1457729725424, 23.0 ], [ 1457730025424, 23.0 ], [ 1457730325424, 23.0 ], [ 1457732425424, 23.1 ], [ 1457734225424, 23.1 ], [ 1457736325424, 23.2 ], [ 1457739625424, 23.2 ], [ 1457739925424, 23.2 ], [ 1457740225424, 23.2 ], [ 1457740525424, 23.2 ], [ 1457742205424, 23.2 ], [ 1457742385424, 23.2 ], [ 1457742565424, 23.2 ], [ 1457742685424, 23.2 ], [ 1457743405424, 23.2 ], [ 1457745145424, 23.2 ], [ 1457745265424, 23.2 ], [ 1457745685424, 23.2 ], [ 1457745745424, 23.2 ], [ 1457745985424, 23.2 ], [ 1457746525424, 23.1 ], [ 1457746585424, 23.1 ], [ 1457747125424, 23.1 ], [ 1457747245424, 23.1 ], [ 1457747785424, 23.1 ], [ 1457747845424, 23.1 ], [ 1457747905424, 23.1 ], [ 1457748025424, 23.1 ], [ 1457748625424, 23.1 ], [ 1457748685424, 23.1 ], [ 1457748925424, 23.1 ], [ 1457750905424, 23.1 ], [ 1457752945424, 23.1 ], [ 1457755105424, 23.0 ], [ 1457755285424, 23.0 ], [ 1457755345424, 23.0 ], [ 1457755405424, 23.0 ], [ 1457755465424, 23.0 ], [ 1457755645424, 23.0 ], [ 1457755705424, 23.0 ], [ 1457755765424, 23.0 ], [ 1457755825424, 23.0 ], [ 1457755885424, 23.0 ], [ 1457756065424, 23.0 ], [ 1457756125424, 23.0 ], [ 1457756185424, 23.0 ], [ 1457756305424, 23.0 ], [ 1457756365424, 23.0 ], [ 1457756425424, 23.0 ], [ 1457756485424, 22.9 ], [ 1457756605424, 22.9 ], [ 1457756665424, 22.9 ], [ 1457756725424, 22.9 ], [ 1457756845424, 22.9 ], [ 1457756905424, 22.9 ], [ 1457757025424, 22.9 ], [ 1457757085424, 22.9 ], [ 1457757145424, 22.9 ], [ 1457757325424, 22.9 ], [ 1457757445424, 22.9 ], [ 1457757685424, 22.9 ], [ 1457757745424, 22.9 ], [ 1457757865424, 22.9 ], [ 1457757925424, 22.9 ], [ 1457757985424, 22.9 ], [ 1457758045424, 22.9 ], [ 1457758105424, 22.9 ], [ 1457758165424, 22.9 ], [ 1457758225424, 22.9 ], [ 1457758285424, 22.9 ], [ 1457758405424, 22.9 ], [ 1457758465424, 22.9 ], [ 1457758525424, 22.8 ], [ 1457758585424, 22.8 ], [ 1457758645424, 22.9 ], [ 1457758765424, 22.8 ], [ 1457758885424, 22.8 ], [ 1457758945424, 22.8 ], [ 1457759005424, 22.8 ], [ 1457759125424, 22.8 ], [ 1457759185424, 22.8 ], [ 1457759305424, 22.8 ], [ 1457759365424, 22.8 ], [ 1457759425424, 22.8 ], [ 1457759485424, 22.8 ], [ 1457759545424, 22.8 ], [ 1457759665424, 22.8 ], [ 1457759725424, 22.8 ], [ 1457759845424, 22.8 ], [ 1457759905424, 22.8 ], [ 1457759965424, 22.8 ], [ 1457760025424, 22.8 ], [ 1457760145424, 22.8 ], [ 1457760205424, 22.7 ], [ 1457760265424, 22.8 ], [ 1457760325424, 22.8 ], [ 1457760445424, 22.8 ], [ 1457760565424, 22.8 ], [ 1457760625424, 22.7 ], [ 1457760685424, 22.7 ], [ 1457760745424, 22.8 ], [ 1457760805424, 22.7 ], [ 1457760865424, 22.7 ], [ 1457760925424, 22.8 ], [ 1457760985424, 22.7 ], [ 1457761105424, 22.7 ], [ 1457761165424, 22.7 ], [ 1457761285424, 22.7 ], [ 1457761345424, 22.7 ], [ 1457761405424, 22.7 ], [ 1457761465424, 22.7 ], [ 1457761525424, 22.7 ], [ 1457761585424, 22.7 ], [ 1457761645424, 22.7 ], [ 1457761765424, 22.7 ], [ 1457761885424, 22.7 ], [ 1457762065424, 22.7 ], [ 1457762078374, 22.7 ], [ 1457762143860, 22.7 ] ],
    "color" : "#ff7f0e"
  } ]
} ]`

**Comment by jkandasa** [comment]
@manusovich can you clear your browser cache and check this once again? or with private browser?

**Comment by manusovich** [comment]
Same error :(
<img width="1463" alt="screen shot 2016-03-12 at 12 00 42 pm" src="https://cloud.githubusercontent.com/assets/2063812/13733365/f923abb6-e95f-11e5-9ca6-59ef5453953c.png">

**Comment by jkandasa** [comment]
@manusovich can you come to https://gitter.im/mycontroller-org/mycontroller I want ask few configurations.

**Comment by jkandasa** [comment]
manusovich Mar 16 23:39 - from gitter chat

--------------------
That was easy  chart requires key defined in each charData item. So if it is not defined - we are getting this error. Key will not be define if user didn't set sensor name (all my sensors with empty name by default)

**Comment by jkandasa** [comment]
add some reference when sensor name is null,
https://github.com/mycontroller-org/mycontroller/blob/0.0.3-alpha1/src/main/java/org/mycontroller/standalone/api/jaxrs/MetricsHandler.java#L306

**Comment by manusovich** [comment]
Hi @jkandasa,

I just checked latest code in development branch. So now i am getting NPE 

```
2016-03-27 02:26:23,355 ERROR [Acme.Utils.ThreadPool(0)-PooledThread: Acme.Serve.Serve$ServeConnection@84ce8b] [org.mycontroller.standalone.api.jaxrs.exception.mappers.ApplicationExceptionMapper:42] ApplicationException,
org.jboss.resteasy.spi.ApplicationException: java.lang.NullPointerException
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:152) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.jboss.resteasy.plugins.server.tjws.TJWSServletDispatcher.service(TJWSServletDispatcher.java:40) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2328) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2282) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at Acme.Serve.Serve$ServeConnection.run(Serve.java:2054) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1402) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Caused by: java.lang.NullPointerException: null
	at org.mycontroller.standalone.api.jaxrs.MetricsHandler.getMetricsDataJsonNVD3WithChartType(MetricsHandler.java:309) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.mycontroller.standalone.api.jaxrs.MetricsHandler.getMetricsDataJsonNVD3(MetricsHandler.java:405) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.mycontroller.standalone.api.jaxrs.MetricsHandler.getMetricsData(MetricsHandler.java:96) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	... 15 common frames omitted
```

request Request URL /mc/rest/metrics/metricsData?chartType=lineChart&timestampFrom=1458959153358&variableId=1&variableId=4&variableId=6&variableId=7

**Comment by jkandasa** [comment]
@manusovich I have added new fix for this. `SensorId + SensorVariableTypeName`. Kindly check and update.

**Comment by manusovich** [comment]
Hi @jkandasa, Looks like it is fixed. Now i have this:
<img width="636" alt="screen shot 2016-04-02 at 9 59 23 am" src="https://cloud.githubusercontent.com/assets/2063812/14227078/ea7d7a10-f8b9-11e5-8147-f217a9de23c0.png">

We have here only 2 graphs because all my temp sensors have the same sensor id. So i think that is my issue and i have to make all sensors with unique ids.

**Comment by jkandasa** [comment]
@manusovich No, there is a possible to have same sensor id's in different nodes. I will add node id also to resolve this. Thank you!

**Comment by jkandasa** [comment]
@manusovich can you check now and update?

**Comment by manusovich** [comment]
Works! :) Thank you!

<img width="836" alt="screen shot 2016-04-02 at 5 51 58 pm" src="https://cloud.githubusercontent.com/assets/2063812/14229552/ab1e5302-f8fb-11e5-9d45-1d5af8cd042e.png">
