### ISSUE TITLE
New nodes keep getting NODE_BC as UID

### ISSUE THREAD

**Issue by githubcdr** [mycontroller-org/mycontroller#188]
Hi,

I noticed something weird, new nodes do not get a new UID for some reason. I have reinstalled mycontroller and uploaded MYSbootloader again, but new nodes to not get an address.

Before I would power on a new node with MYSloader1.1 or 1.3 and it would appear with UID "NODE_BC" I click on it and assign an EUI and reboot the node.

When I change the EUI, I get another "NODE_BC", what am I doing wrong? I feel like too much OTA's caused a corruption in the bootloader, but I'm not sure.

mqtt logs;

```
mygateway1-out/255/255/3/0/3 (null)
mygateway1-in/255/255/3/1/4 2
mygateway1-out/255/255/3/0/3 (null)
mygateway1-in/255/255/3/1/4 2
mygateway1-out/255/255/3/0/3 (null)
mygateway1-in/255/255/3/1/4 2
mygateway1-out/255/255/3/0/3 (null)
mygateway1-in/255/255/3/1/4 2
```

mycontroller logs;

```
Exception in thread "Thread-27" java.lang.NullPointerException
        at org.mycontroller.standalone.message.McMessageEngine.setSensorOtherData(McMessageEngine.java:747)
        at org.mycontroller.standalone.message.McMessageEngine.streamSubMessageTypeSelector(McMessageEngine.java:317)
        at org.mycontroller.standalone.message.McMessageEngine.execute(McMessageEngine.java:107)
        at org.mycontroller.standalone.message.McMessageEngine.run(McMessageEngine.java:786)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-29" java.lang.NullPointerException
        at org.mycontroller.standalone.message.McMessageEngine.setSensorOtherData(McMessageEngine.java:747)
        at org.mycontroller.standalone.message.McMessageEngine.streamSubMessageTypeSelector(McMessageEngine.java:317)
        at org.mycontroller.standalone.message.McMessageEngine.execute(McMessageEngine.java:107)
        at org.mycontroller.standalone.message.McMessageEngine.run(McMessageEngine.java:786)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-31" java.lang.NullPointerException
        at org.mycontroller.standalone.message.McMessageEngine.setSensorOtherData(McMessageEngine.java:747)
        at org.mycontroller.standalone.message.McMessageEngine.streamSubMessageTypeSelector(McMessageEngine.java:317)
        at org.mycontroller.standalone.message.McMessageEngine.execute(McMessageEngine.java:107)
        at org.mycontroller.standalone.message.McMessageEngine.run(McMessageEngine.java:786)

```

**Comment by jkandasa** [comment]
@githubcdr Thank you! good catch. This should be bug. I will confirm.

**Comment by jkandasa** [comment]
It is bug! Thank you! Will fix it soon.

**Comment by jkandasa** [comment]
@githubcdr Please reopen this issue, if you face this issue again.

**Comment by MPParsley** [comment]
@jkandasa, still experiencing this issue in 0.0.3.Alpha2. When I try to change the ID from NODE_BC to 100 I get: "400: Bad request A node available with this EUI."
