### ISSUE TITLE
Random crash (0.0.3.Final-SNAPSHOT)

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#239]
```
2016-08-08 03:21:42,681 ERROR [Quartz_Scheduler_Worker-2] [org.quartz.core.JobRunShell:186] Job node_alive_status_job threw an unhandled Exception: 
java.lang.AbstractMethodError: null
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:652) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcDatabaseResults.getLong(JdbcDatabaseResults.java:138) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection$OneLongWrapper.mapRow(JdbcDatabaseConnection.java:336) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection$OneLongWrapper.mapRow(JdbcDatabaseConnection.java:333) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForOne(JdbcDatabaseConnection.java:283) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForLong(JdbcDatabaseConnection.java:210) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForLong(JdbcDatabaseConnection.java:205) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.testConnection(JdbcPooledConnectionSource.java:350) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.getReadWriteConnection(JdbcPooledConnectionSource.java:127) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.getReadOnlyConnection(JdbcPooledConnectionSource.java:111) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:196) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.stmt.StatementExecutor.queryForAll(StatementExecutor.java:118) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.dao.BaseDaoImpl.queryForAll(BaseDaoImpl.java:241) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.mycontroller.standalone.db.dao.BaseAbstractDaoImpl.getAll(BaseAbstractDaoImpl.java:252) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.mycontroller.standalone.jobs.NodeAliveStatusJob.checkHearbeat(NodeAliveStatusJob.java:86) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.mycontroller.standalone.jobs.NodeAliveStatusJob.doRun(NodeAliveStatusJob.java:63) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.knowm.sundial.Job.execute(Job.java:57) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:178) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.quartz.core.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:515) [mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
2016-08-08 03:21:42,693 ERROR [Quartz_Scheduler_Worker-2] [org.quartz.ErrorLoggingScheduleListener:1158] Job (node_alive_status_job threw an exception.
org.quartz.exceptions.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:187) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.quartz.core.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:515) [mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
Caused by: java.lang.AbstractMethodError: null
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:652) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcDatabaseResults.getLong(JdbcDatabaseResults.java:138) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection$OneLongWrapper.mapRow(JdbcDatabaseConnection.java:336) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection$OneLongWrapper.mapRow(JdbcDatabaseConnection.java:333) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForOne(JdbcDatabaseConnection.java:283) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForLong(JdbcDatabaseConnection.java:210) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForLong(JdbcDatabaseConnection.java:205) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.testConnection(JdbcPooledConnectionSource.java:350) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.getReadWriteConnection(JdbcPooledConnectionSource.java:127) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.getReadOnlyConnection(JdbcPooledConnectionSource.java:111) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:196) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.stmt.StatementExecutor.queryForAll(StatementExecutor.java:118) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at com.j256.ormlite.dao.BaseDaoImpl.queryForAll(BaseDaoImpl.java:241) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.mycontroller.standalone.db.dao.BaseAbstractDaoImpl.getAll(BaseAbstractDaoImpl.java:252) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.mycontroller.standalone.jobs.NodeAliveStatusJob.checkHearbeat(NodeAliveStatusJob.java:86) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.mycontroller.standalone.jobs.NodeAliveStatusJob.doRun(NodeAliveStatusJob.java:63) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.knowm.sundial.Job.execute(Job.java:57) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:178) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	... 1 common frames omitted
Exception in thread "Thread-295144" java.lang.AbstractMethodError
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:652)
	at com.j256.ormlite.jdbc.JdbcDatabaseResults.getLong(JdbcDatabaseResults.java:138)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection$OneLongWrapper.mapRow(JdbcDatabaseConnection.java:336)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection$OneLongWrapper.mapRow(JdbcDatabaseConnection.java:333)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForOne(JdbcDatabaseConnection.java:283)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForLong(JdbcDatabaseConnection.java:210)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForLong(JdbcDatabaseConnection.java:205)
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.testConnection(JdbcPooledConnectionSource.java:350)
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.getReadWriteConnection(JdbcPooledConnectionSource.java:127)
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.getReadOnlyConnection(JdbcPooledConnectionSource.java:111)
	at com.j256.ormlite.dao.BaseDaoImpl.queryForFirst(BaseDaoImpl.java:231)
	at com.j256.ormlite.stmt.QueryBuilder.queryForFirst(QueryBuilder.java:375)
	at org.mycontroller.standalone.db.dao.NodeDaoImpl.get(NodeDaoImpl.java:58)
	at org.mycontroller.standalone.message.McMessageEngine.getNode(McMessageEngine.java:771)
	at org.mycontroller.standalone.message.McMessageEngine.isNodeRegistered(McMessageEngine.java:162)
	at org.mycontroller.standalone.message.McMessageEngine.execute(McMessageEngine.java:115)
	at org.mycontroller.standalone.message.McMessageEngine.run(McMessageEngine.java:962)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-295145" java.lang.AbstractMethodError
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:652)
	at com.j256.ormlite.jdbc.JdbcDatabaseResults.getLong(JdbcDatabaseResults.java:138)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection$OneLongWrapper.mapRow(JdbcDatabaseConnection.java:336)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection$OneLongWrapper.mapRow(JdbcDatabaseConnection.java:333)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForOne(JdbcDatabaseConnection.java:283)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForLong(JdbcDatabaseConnection.java:210)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForLong(JdbcDatabaseConnection.java:205)
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.testConnection(JdbcPooledConnectionSource.java:350)
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.getReadWriteConnection(JdbcPooledConnectionSource.java:127)
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.getReadOnlyConnection(JdbcPooledConnectionSource.java:111)
	at com.j256.ormlite.dao.BaseDaoImpl.queryForFirst(BaseDaoImpl.java:231)
	at com.j256.ormlite.stmt.QueryBuilder.queryForFirst(QueryBuilder.java:375)
	at org.mycontroller.standalone.db.dao.NodeDaoImpl.get(NodeDaoImpl.java:58)
	at org.mycontroller.standalone.message.McMessageEngine.getNode(McMessageEngine.java:771)
	at org.mycontroller.standalone.message.McMessageEngine.isNodeRegistered(McMessageEngine.java:162)
	at org.mycontroller.standalone.message.McMessageEngine.execute(McMessageEngine.java:115)
	at org.mycontroller.standalone.message.McMessageEngine.run(McMessageEngine.java:962)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-295146" java.lang.AbstractMethodError
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:652)
	at com.j256.ormlite.jdbc.JdbcDatabaseResults.getLong(JdbcDatabaseResults.java:138)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection$OneLongWrapper.mapRow(JdbcDatabaseConnection.java:336)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection$OneLongWrapper.mapRow(JdbcDatabaseConnection.java:333)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForOne(JdbcDatabaseConnection.java:283)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForLong(JdbcDatabaseConnection.java:210)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForLong(JdbcDatabaseConnection.java:205)
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.testConnection(JdbcPooledConnectionSource.java:350)
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.getReadWriteConnection(JdbcPooledConnectionSource.java:127)
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.getReadOnlyConnection(JdbcPooledConnectionSource.java:111)
	at com.j256.ormlite.dao.BaseDaoImpl.queryForFirst(BaseDaoImpl.java:231)
	at com.j256.ormlite.stmt.QueryBuilder.queryForFirst(QueryBuilder.java:375)
	at org.mycontroller.standalone.db.dao.NodeDaoImpl.get(NodeDaoImpl.java:58)
	at org.mycontroller.standalone.message.McMessageEngine.getNode(McMessageEngine.java:771)
	at org.mycontroller.standalone.message.McMessageEngine.isNodeRegistered(McMessageEngine.java:162)
	at org.mycontroller.standalone.message.McMessageEngine.execute(McMessageEngine.java:115)
	at org.mycontroller.standalone.message.McMessageEngine.run(McMessageEngine.java:962)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-295147" java.lang.AbstractMethodError
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:652)
	at com.j256.ormlite.jdbc.JdbcDatabaseResults.getLong(JdbcDatabaseResults.java:138)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection$OneLongWrapper.mapRow(JdbcDatabaseConnection.java:336)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection$OneLongWrapper.mapRow(JdbcDatabaseConnection.java:333)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForOne(JdbcDatabaseConnection.java:283)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForLong(JdbcDatabaseConnection.java:210)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForLong(JdbcDatabaseConnection.java:205)
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.testConnection(JdbcPooledConnectionSource.java:350)
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.getReadWriteConnection(JdbcPooledConnectionSource.java:127)
	at com.j256.ormlite.jdbc.JdbcPooledConnectionSource.getReadOnlyConnection(JdbcPooledConnectionSource.java:111)
	at com.j256.ormlite.dao.BaseDaoImpl.queryForFirst(BaseDaoImpl.java:231)
	at com.j256.ormlite.stmt.QueryBuilder.queryForFirst(QueryBuilder.java:375)
	at org.mycontroller.standalone.db.dao.NodeDaoImpl.get(NodeDaoImpl.java:58)
	at org.mycontroller.standalone.message.McMessageEngine.getNode(McMessageEngine.java:771)
	at org.mycontroller.standalone.message.McMessageEngine.internalSubMessageTypeSelector(McMessageEngine.java:221)
	at org.mycontroller.standalone.message.McMessageEngine.execute(McMessageEngine.java:129)
	at org.mycontroller.standalone.message.McMessageEngine.run(McMessageEngine.java:962)
	at java.lang.Thread.run(Thread.java:745)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x767c96f4, pid=2059, tid=0x6ac2f460
#
# JRE version: Java(TM) SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)
# Java VM: Java HotSpot(TM) Client VM (25.101-b13 mixed mode linux-arm )
# Problematic frame:
# V  [libjvm.so+0x49b6f4]  Symbol::as_klass_external_name() const+0x4
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/pi/mycontroller/bin/hs_err_pid2059.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

I am not totally sure if this might be hardware related but an unhandelt exception seems like a software problem.

**Comment by cimba007** [comment]
Might be related to this?

Gateway -> action -> discover (Server Error 500)
`
2016-08-08 13:11:16,516 INFO [Acme.Utils.ThreadPool(5)-PooledThread: Acme.Serve.Serve$ServeConnection@19987d4] [org.mycontroller.standalone.gateway.mqtt.MqttGatewayImpl:70] MQTT Gateway[tcp://localhost:1883] connected successfully..
2016-08-08 13:11:25,696 ERROR [Acme.Utils.ThreadPool(5)-PooledThread: Acme.Serve.Serve$ServeConnection@19987d4] [org.mycontroller.standalone.api.jaxrs.exception.mappers.ApplicationExceptionMapper:42] ApplicationException,
org.jboss.resteasy.spi.ApplicationException: java.lang.NoClassDefFoundError: org/mycontroller/standalone/provider/mysensors/MySensorsEngine
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:152) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395) [mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202) [mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221) [mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.jboss.resteasy.plugins.server.tjws.TJWSServletDispatcher.service(TJWSServletDispatcher.java:40) [mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820) [mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2328) [mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2282) [mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at Acme.Serve.Serve$ServeConnection.run(Serve.java:2054) [mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1402) [mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: org/mycontroller/standalone/provider/mysensors/MySensorsEngine
	at org.mycontroller.standalone.provider.mysensors.MySensorsRawMessage.<init>(MySensorsRawMessage.java:95) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.mycontroller.standalone.provider.mysensors.MySensorsProviderBridge.executeMcMessage(MySensorsProviderBridge.java:45) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.mycontroller.standalone.message.McMessageUtils.sendToProviderBridge(McMessageUtils.java:557) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.mycontroller.standalone.message.McActionEngine.discover(McActionEngine.java:290) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.mycontroller.standalone.api.GatewayApi.executeNodeDiscover(GatewayApi.java:129) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at org.mycontroller.standalone.api.jaxrs.GatewayHandler.executeNodeDiscover(GatewayHandler.java:152) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139) ~[mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-single.jar:0.0.3.Final-SNAPSHOT]
	... 15 common frames omitted
`

**Comment by jkandasa** [comment]
@cimba007 Thanks to report this exception.  I will check this

**Comment by jkandasa** [comment]
@cimba007 can you check with recent build?
