### ISSUE TITLE
New Timer Time.

### ISSUE THREAD

**Issue by Gouds** [mycontroller-org/mycontroller#272]
When Running the new build and adding/editing a timer time. The system errors out. Removing all time information on the Timer job.

2016-09-02 17:34:46,930 ERROR [Acme.Utils.ThreadPool(4)-PooledThread: Acme.Serve.Serve$ServeConnection@bfa502] [org.mycontroller.standalone.api.jaxrs.mixins.deserializers.TriggerTimeDeserializer:46] Trigger time parse error, input:[-62167280400000]
2016-09-02 17:35:18,730 ERROR [Acme.Utils.ThreadPool(0)-PooledThread: Acme.Serve.Serve$ServeConnection@80fa] [org.mycontroller.standalone.api.jaxrs.mixins.deserializers.TriggerTimeDeserializer:46] Trigger time parse error, input:[-62167320000000]
2016-09-02 17:35:18,770 ERROR [Acme.Utils.ThreadPool(0)-PooledThread: Acme.Serve.Serve$ServeConnection@80fa] [org.mycontroller.standalone.api.jaxrs.exception.mappers.ApplicationExceptionMapper:42] ApplicationException,
org.jboss.resteasy.spi.ApplicationException: java.lang.NullPointerException
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:152)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.tjws.TJWSServletDispatcher.service(TJWSServletDispatcher.java:40)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2328)
	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2282)
	at Acme.Serve.Serve$ServeConnection.run(Serve.java:2054)
	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1402)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException: null
	at org.mycontroller.standalone.scheduler.SchedulerUtils.loadTimerJob(SchedulerUtils.java:199)
	at org.mycontroller.standalone.scheduler.SchedulerUtils.loadTimerJob(SchedulerUtils.java:156)
	at org.mycontroller.standalone.timer.TimerUtils.updateTimer(TimerUtils.java:341)
	at org.mycontroller.standalone.api.TimerApi.update(TimerApi.java:54)
	at org.mycontroller.standalone.api.jaxrs.TimerHandler.update(TimerHandler.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	... 15 common frames omitted

**Comment by jkandasa** [comment]
@Gouds can you refresh you browser (F5), if still face clear cache and check.

**Comment by Gouds** [comment]
Complete the above and resolved the issue. The timer time is now resolved based on the latest build.
