### ISSUE TITLE
Resource log not working

### ISSUE THREAD

**Issue by wengjjpaul** [mycontroller-org/mycontroller#294]
My resource log is not logging. Also graphs are not working. Any idea?

```
2016-11-01 11:18:06,233 ERROR [Quartz_Scheduler_Worker-1] [org.mycontroller.standalone.db.dao.MetricsDoubleTypeDeviceDaoImpl:57] unable to delete metric:[MetricsDoubleTypeDevice(sensorVariable=null, timestamp=1477805709036, samples=null, min=null, max=null, avg=null, aggregationType=SIX_HOURS, timestampFrom=null, timestampTo=null)]
org.h2.jdbc.JdbcSQLException: General error: "java.lang.RuntimeException: page[1045] data leaf table:68 METRICS_DOUBLE_TYPE_DEVICE entries:8 parent:1012 keys:[98056, 98057, 98058, 98059, 98060, 98103, 98104, 98105] offsets:[2007, 1985, 1966, 1937, 1915, 1873, 1851, 1832] parent 1012 expected 1645"; SQL statement:
DELETE FROM `metrics_double_type_device` WHERE (`aggregationType` = 4 AND `timestamp` <= 1477805709036 )  [50000-176]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.message.DbException.get(DbException.java:167) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.message.DbException.convert(DbException.java:294) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.command.Command.executeUpdate(Command.java:262) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:158) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:144) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at com.j256.ormlite.jdbc.JdbcCompiledStatement.runUpdate(JdbcCompiledStatement.java:48) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at com.j256.ormlite.stmt.StatementExecutor.delete(StatementExecutor.java:541) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at com.j256.ormlite.dao.BaseDaoImpl.delete(BaseDaoImpl.java:468) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.mycontroller.standalone.db.dao.MetricsDoubleTypeDeviceDaoImpl.deletePrevious(MetricsDoubleTypeDeviceDaoImpl.java:54) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.mycontroller.standalone.metrics.MetricsAggregationBase.purgeMetricTables(MetricsAggregationBase.java:490) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.mycontroller.standalone.metrics.MetricsAggregationBase.runAggregation(MetricsAggregationBase.java:392) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.mycontroller.standalone.metrics.jobs.MetricsAggregationJob.doRun(MetricsAggregationJob.java:35) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.knowm.sundial.Job.execute(Job.java:57) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:178) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.quartz.core.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:515) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
Caused by: java.lang.RuntimeException: page[1045] data leaf table:68 METRICS_DOUBLE_TYPE_DEVICE entries:8 parent:1012 keys:[98056, 98057, 98058, 98059, 98060, 98103, 98104, 98105] offsets:[2007, 1985, 1966, 1937, 1915, 1873, 1851, 1832] parent 1012 expected 1645
    at org.h2.message.DbException.throwInternalError(DbException.java:241) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataIndex.getPage(PageDataIndex.java:247) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataNode.getNextPage(PageDataNode.java:233) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataLeaf.getNextPage(PageDataLeaf.java:400) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataCursor.nextRow(PageDataCursor.java:95) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataCursor.next(PageDataCursor.java:53) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.IndexCursor.next(IndexCursor.java:278) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.table.TableFilter.next(TableFilter.java:361) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.command.dml.Delete.update(Delete.java:71) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.command.CommandContainer.update(CommandContainer.java:79) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.command.Command.executeUpdate(Command.java:254) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    ... 12 common frames omitted
2016-11-01 11:18:06,283 ERROR [Quartz_Scheduler_Worker-1] [org.mycontroller.standalone.db.dao.MetricsDoubleTypeDeviceDaoImpl:57] unable to delete metric:[MetricsDoubleTypeDevice(sensorVariable=null, timestamp=1477805709036, samples=null, min=null, max=null, avg=null, aggregationType=TWELVE_HOURS, timestampFrom=null, timestampTo=null)]
org.h2.jdbc.JdbcSQLException: General error: "java.lang.RuntimeException: page[1045] data leaf table:68 METRICS_DOUBLE_TYPE_DEVICE entries:8 parent:1012 keys:[98056, 98057, 98058, 98059, 98060, 98103, 98104, 98105] offsets:[2007, 1985, 1966, 1937, 1915, 1873, 1851, 1832] parent 1012 expected 1645"; SQL statement:
DELETE FROM `metrics_double_type_device` WHERE (`aggregationType` = 5 AND `timestamp` <= 1477805709036 )  [50000-176]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.message.DbException.get(DbException.java:167) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.message.DbException.convert(DbException.java:294) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.command.Command.executeUpdate(Command.java:262) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:158) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:144) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at com.j256.ormlite.jdbc.JdbcCompiledStatement.runUpdate(JdbcCompiledStatement.java:48) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at com.j256.ormlite.stmt.StatementExecutor.delete(StatementExecutor.java:541) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at com.j256.ormlite.dao.BaseDaoImpl.delete(BaseDaoImpl.java:468) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.mycontroller.standalone.db.dao.MetricsDoubleTypeDeviceDaoImpl.deletePrevious(MetricsDoubleTypeDeviceDaoImpl.java:54) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.mycontroller.standalone.metrics.MetricsAggregationBase.purgeMetricTables(MetricsAggregationBase.java:495) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.mycontroller.standalone.metrics.MetricsAggregationBase.runAggregation(MetricsAggregationBase.java:392) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.mycontroller.standalone.metrics.jobs.MetricsAggregationJob.doRun(MetricsAggregationJob.java:35) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.knowm.sundial.Job.execute(Job.java:57) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:178) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.quartz.core.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:515) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
Caused by: java.lang.RuntimeException: page[1045] data leaf table:68 METRICS_DOUBLE_TYPE_DEVICE entries:8 parent:1012 keys:[98056, 98057, 98058, 98059, 98060, 98103, 98104, 98105] offsets:[2007, 1985, 1966, 1937, 1915, 1873, 1851, 1832] parent 1012 expected 1645
    at org.h2.message.DbException.throwInternalError(DbException.java:241) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataIndex.getPage(PageDataIndex.java:247) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataNode.getNextPage(PageDataNode.java:233) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataLeaf.getNextPage(PageDataLeaf.java:400) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataCursor.nextRow(PageDataCursor.java:95) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataCursor.next(PageDataCursor.java:53) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.IndexCursor.next(IndexCursor.java:278) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.table.TableFilter.next(TableFilter.java:361) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.command.dml.Delete.update(Delete.java:71) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.command.CommandContainer.update(CommandContainer.java:79) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.command.Command.executeUpdate(Command.java:254) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    ... 12 common frames omitted
2016-11-01 11:18:06,335 ERROR [Quartz_Scheduler_Worker-1] [org.mycontroller.standalone.db.dao.MetricsDoubleTypeDeviceDaoImpl:57] unable to delete metric:[MetricsDoubleTypeDevice(sensorVariable=null, timestamp=1320290286287, samples=null, min=null, max=null, avg=null, aggregationType=ONE_DAY, timestampFrom=null, timestampTo=null)]
org.h2.jdbc.JdbcSQLException: General error: "java.lang.RuntimeException: page[1045] data leaf table:68 METRICS_DOUBLE_TYPE_DEVICE entries:8 parent:1012 keys:[98056, 98057, 98058, 98059, 98060, 98103, 98104, 98105] offsets:[2007, 1985, 1966, 1937, 1915, 1873, 1851, 1832] parent 1012 expected 1645"; SQL statement:
DELETE FROM `metrics_double_type_device` WHERE (`aggregationType` = 6 AND `timestamp` <= 1320290286287 )  [50000-176]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.message.DbException.get(DbException.java:167) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.message.DbException.convert(DbException.java:294) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.command.Command.executeUpdate(Command.java:262) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:158) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:144) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at com.j256.ormlite.jdbc.JdbcCompiledStatement.runUpdate(JdbcCompiledStatement.java:48) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at com.j256.ormlite.stmt.StatementExecutor.delete(StatementExecutor.java:541) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at com.j256.ormlite.dao.BaseDaoImpl.delete(BaseDaoImpl.java:468) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.mycontroller.standalone.db.dao.MetricsDoubleTypeDeviceDaoImpl.deletePrevious(MetricsDoubleTypeDeviceDaoImpl.java:54) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.mycontroller.standalone.metrics.MetricsAggregationBase.purgeMetricTables(MetricsAggregationBase.java:500) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.mycontroller.standalone.metrics.MetricsAggregationBase.runAggregation(MetricsAggregationBase.java:392) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.mycontroller.standalone.metrics.jobs.MetricsAggregationJob.doRun(MetricsAggregationJob.java:35) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.knowm.sundial.Job.execute(Job.java:57) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:178) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.quartz.core.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:515) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
Caused by: java.lang.RuntimeException: page[1045] data leaf table:68 METRICS_DOUBLE_TYPE_DEVICE entries:8 parent:1012 keys:[98056, 98057, 98058, 98059, 98060, 98103, 98104, 98105] offsets:[2007, 1985, 1966, 1937, 1915, 1873, 1851, 1832] parent 1012 expected 1645
    at org.h2.message.DbException.throwInternalError(DbException.java:241) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataIndex.getPage(PageDataIndex.java:247) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataNode.getNextPage(PageDataNode.java:233) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataLeaf.getNextPage(PageDataLeaf.java:400) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataCursor.nextRow(PageDataCursor.java:95) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.PageDataCursor.next(PageDataCursor.java:53) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.index.IndexCursor.next(IndexCursor.java:278) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.table.TableFilter.next(TableFilter.java:361) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.command.dml.Delete.update(Delete.java:71) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.command.CommandContainer.update(CommandContainer.java:79) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    at org.h2.command.Command.executeUpdate(Command.java:254) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
    ... 12 common frames omitted
```

**Comment by jkandasa** [comment]
@wengjjpaul looks like your database has been corrupted

**Comment by jkandasa** [comment]
@wengjjpaul reinstall or stop mycontroller and delete `mycontroller/conf/mycontroller.h2.db` and start server.

**Comment by jkandasa** [comment]
@wengjjpaul if you do not face this issue we can close this?

**Comment by wengjjpaul** [comment]
Fixed after a reinstall.
