### ISSUE TITLE
[SnapShot] Unknown column name 'blocks' in table firmware

### ISSUE THREAD

**Issue by wengjjpaul** [mycontroller-org/mycontroller#303]
Got this error when deleting firmware version

500: Internal server error
java.lang.IllegalArgumentException: Unknown column name 'blocks' in table firmware
```
 2016-11-10 18:17:25,608 ERROR [Acme.Utils.ThreadPool(4)-PooledThread: Acme.Serve.Serve$ServeConnection@6fbf3f] [org.mycontroller.standalone.api.jaxrs.exception.mappers.ApplicationExceptionMapper:42] ApplicationException,
 org.jboss.resteasy.spi.ApplicationException: java.lang.IllegalArgumentException: Unknown column name 'blocks' in table firmware
 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:152)
 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
 	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
 	at org.jboss.resteasy.plugins.server.tjws.TJWSServletDispatcher.service(TJWSServletDispatcher.java:40)
 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2328)
 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2282)
 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:2054)
 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1402)
 	at java.lang.Thread.run(Thread.java:744)
 Caused by: java.lang.IllegalArgumentException: Unknown column name 'blocks' in table firmware
 	at com.j256.ormlite.table.TableInfo.getFieldTypeByColumnName(TableInfo.java:155)
 	at com.j256.ormlite.stmt.StatementBuilder.verifyColumnName(StatementBuilder.java:183)
 	at com.j256.ormlite.stmt.QueryBuilder.addSelectColumnToList(QueryBuilder.java:636)
 	at com.j256.ormlite.stmt.QueryBuilder.selectColumns(QueryBuilder.java:117)
 	at org.mycontroller.standalone.db.dao.FirmwareDaoImpl.getAll(FirmwareDaoImpl.java:85)
 	at org.mycontroller.standalone.db.dao.FirmwareDaoImpl.getAllFirmwareByVersion(FirmwareDaoImpl.java:79)
 	at org.mycontroller.standalone.firmware.FirmwareUtils.deleteFirmwareVersion(FirmwareUtils.java:202)
 	at org.mycontroller.standalone.api.jaxrs.FirmwareHandler.deleteFirmwareVersion(FirmwareHandler.java:185)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:483)
 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
 	... 15 common frames omitted
```

**Comment by jkandasa** [comment]
Deleting `Firmware Type` also giving similar issue
