### ISSUE TITLE
when send data to VAR_5 throws NPE

### ISSUE THREAD

**Issue by jkandasa** [mycontroller-org/mycontroller#397]
Issue reported by @nagurao

I have come across the following when I use V_VAR5 in my code. Is V_VAR5 used for only some specific purpose?
Just to give you a little background I am using V_VAR4 and V_VAR5 to send the sunrise and sunset time back to gateway.
 
My presentation code is as follows:
```
present(4, S_CUSTOM, "Sunrise Trigger Time");
present(5, S_CUSTOM, "Sunset Trigger Time");
```
In the function where I send the data back to gateway I have the code as follows:

```
MyMessage sunriseTriggerTimeMessage(SUNRISE_TRIGGER_TIME_ID, V_VAR4);
send(sunriseTriggerTimeMessage.set(<time_in_HH:MM_format>));
MyMessage sunsetTriggerTimeMessage(SUNSET_TRIGGER_TIME_ID, V_VAR5);
send(sunsetTriggerTimeMessage.set(<time_in_HH:MM_format>));
``` 
I have following 3 cases can you please check and let me know where I am going wrong?
 
 
Case1: (Sunrise in V_VAR4, & Sunset in V_VAR5) The gateway is able to receive the sunrise time correctly, but the following error is thrown when sunset time is received.

```
2017-09-24 14:21:27,982 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;255;3;0;1;]
2017-09-24 14:21:27,996 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=1,c=0,t=23,pt=0,l=18,sg=0:Sunrise Time (sec)]
2017-09-24 14:21:28,002 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;1;0;0;23;Sunrise Time (sec)]
2017-09-24 14:21:28,017 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=2,c=0,t=23,pt=0,l=17,sg=0:Sunset Time (sec)]
2017-09-24 14:21:28,021 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;2;0;0;23;Sunset Time (sec)]
2017-09-24 14:21:28,038 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=3,c=0,t=23,pt=0,l=11,sg=0:Last Update]
2017-09-24 14:21:28,043 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;3;0;0;23;Last Update]
2017-09-24 14:21:28,056 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=4,c=0,t=23,pt=0,l=20,sg=0:Sunrise Trigger Time]
2017-09-24 14:21:28,060 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;4;0;0;23;Sunrise Trigger Time]
2017-09-24 14:21:28,078 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=5,c=0,t=23,pt=0,l=19,sg=0:Sunset Trigger Time]
2017-09-24 14:21:28,084 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;5;0;0;23;Sunset Trigger Time]
2017-09-24 14:21:30,491 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=4,c=1,t=27,pt=0,l=5,sg=0:06:35]
2017-09-24 14:21:30,493 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;4;1;0;27;06:35]
 
2017-09-24 14:21:30,782 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=5,c=1,t=28,pt=0,l=5,sg=0:18:41]
2017-09-24 14:21:30,785 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;5;1;0;28;18:41]
2017-09-24 14:21:30,819 ERROR [Thread-6] [org.mycontroller.standalone.message.MessageMonitorThread:119] Throws exception while processing!, [RawMessage(gatewayId=1, data=254;5;1;0;28;18:41, subData=null, isTxMessage=false, networkType=MY_SENSORS, timestamp=1506243090762)]
java.lang.NullPointerException: null
        at org.mycontroller.standalone.message.McMessageUtils.getPayLoadType(McMessageUtils.java:405)
        at org.mycontroller.standalone.message.McMessageEngine.recordSetTypeData(McMessageEngine.java:958)
        at org.mycontroller.standalone.message.McMessageEngine.execute(McMessageEngine.java:108)
        at org.mycontroller.standalone.message.McMessageEngine.run(McMessageEngine.java:1090)
        at org.mycontroller.standalone.message.McMessageUtils.sendToMcMessageEngine(McMessageUtils.java:662)
        at org.mycontroller.standalone.provider.mysensors.MySensorsProviderBridge.executeRawMessage(MySensorsProviderBridge.java:59)
        at org.mycontroller.standalone.message.McMessageUtils.sendToProviderBridge(McMessageUtils.java:571)
        at org.mycontroller.standalone.message.MessageMonitorThread.processRawMessage(MessageMonitorThread.java:107)
        at org.mycontroller.standalone.message.MessageMonitorThread.run(MessageMonitorThread.java:182)
        at java.lang.Thread.run(Thread.java:745)
``` 
 
Case2: (Sunrise in V_VAR4, & Sunset in V_VAR4) In case if I use V_VAR4 for both sunrise and sunset while sending the values to gateway I get no error (no other code changes)

```
2017-09-24 14:33:17,962 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=1,c=0,t=23,pt=0,l=18,sg=0:Sunrise Time (sec)]
2017-09-24 14:33:17,966 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;1;0;0;23;Sunrise Time (sec)]
2017-09-24 14:33:17,984 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=2,c=0,t=23,pt=0,l=17,sg=0:Sunset Time (sec)]
2017-09-24 14:33:17,988 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;2;0;0;23;Sunset Time (sec)]
2017-09-24 14:33:18,008 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=3,c=0,t=23,pt=0,l=11,sg=0:Last Update]
2017-09-24 14:33:18,012 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;3;0;0;23;Last Update]
2017-09-24 14:33:18,031 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=4,c=0,t=23,pt=0,l=20,sg=0:Sunrise Trigger Time]
2017-09-24 14:33:18,034 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;4;0;0;23;Sunrise Trigger Time]
2017-09-24 14:33:18,053 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=5,c=0,t=23,pt=0,l=19,sg=0:Sunset Trigger Time]
2017-09-24 14:33:18,059 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;5;0;0;23;Sunset Trigger Time]
2017-09-24 14:34:33,713 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=4,c=1,t=27,pt=0,l=5,sg=0:06:35]
2017-09-24 14:34:33,715 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;4;1;0;27;06:35]
2017-09-24 14:34:33,888 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=5,c=1,t=27,pt=0,l=5,sg=0:18:41]
2017-09-24 14:34:33,890 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;5;1;0;27;18:41]
```

Case3: (Sunrise in V_VAR5, & Sunset in V_VAR5) In case if I use V_VAR5 for both sunrise and sunset while sending the values to gateway I get the same error for both sunrise and sunset

```
2017-09-24 14:43:10,002 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=1,c=0,t=23,pt=0,l=18,sg=0:Sunrise Time (sec)]
2017-09-24 14:43:10,010 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;1;0;0;23;Sunrise Time (sec)]
2017-09-24 14:43:10,034 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=2,c=0,t=23,pt=0,l=17,sg=0:Sunset Time (sec)]
2017-09-24 14:43:10,037 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;2;0;0;23;Sunset Time (sec)]
2017-09-24 14:43:10,048 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=3,c=0,t=23,pt=0,l=11,sg=0:Last Update]
2017-09-24 14:43:10,051 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;3;0;0;23;Last Update]
2017-09-24 14:43:10,072 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=4,c=0,t=23,pt=0,l=20,sg=0:Sunrise Trigger Time]
2017-09-24 14:43:10,076 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;4;0;0;23;Sunrise Trigger Time]
2017-09-24 14:43:10,096 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=5,c=0,t=23,pt=0,l=19,sg=0:Sunset Trigger Time]
2017-09-24 14:43:10,100 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;5;0;0;23;Sunset Trigger Time]
2017-09-24 14:44:25,438 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=4,c=1,t=28,pt=0,l=5,sg=0:06:35]
2017-09-24 14:44:25,443 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;4;1;0;28;06:35]
2017-09-24 14:44:25,726 ERROR [Thread-6] [org.mycontroller.standalone.message.MessageMonitorThread:119] Throws exception while processing!, [RawMessage(gatewayId=1, data=254;4;1;0;28;06:35, subData=null, isTxMessage=false, networkType=MY_SENSORS, timestamp=1506244465445)]
java.lang.NullPointerException: null
        at org.mycontroller.standalone.message.McMessageUtils.getPayLoadType(McMessageUtils.java:405)
        at org.mycontroller.standalone.message.McMessageEngine.recordSetTypeData(McMessageEngine.java:958)
       at org.mycontroller.standalone.message.McMessageEngine.execute(McMessageEngine.java:108)
        at org.mycontroller.standalone.message.McMessageEngine.run(McMessageEngine.java:1090)
        at org.mycontroller.standalone.message.McMessageUtils.sendToMcMessageEngine(McMessageUtils.java:662)
        at org.mycontroller.standalone.provider.mysensors.MySensorsProviderBridge.executeRawMessage(MySensorsProviderBridge.java:59)
        at org.mycontroller.standalone.message.McMessageUtils.sendToProviderBridge(McMessageUtils.java:571)
        at org.mycontroller.standalone.message.MessageMonitorThread.processRawMessage(MessageMonitorThread.java:107)
        at org.mycontroller.standalone.message.MessageMonitorThread.run(MessageMonitorThread.java:182)
        at java.lang.Thread.run(Thread.java:745)
2017-09-24 14:44:26,009 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSP:MSG:READ 254-10-0 s=5,c=1,t=28,pt=0,l=5,sg=0:18:41]
2017-09-24 14:44:26,011 DEBUG [Thread-7] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[254;5;1;0;28;18:41]
2017-09-24 14:44:26,110 ERROR [Thread-6] [org.mycontroller.standalone.message.MessageMonitorThread:119] Throws exception while processing!, [RawMessage(gatewayId=1, data=254;5;1;0;28;18:41, subData=null, isTxMessage=false, networkType=MY_SENSORS, timestamp=1506244466012)]
java.lang.NullPointerException: null
        at org.mycontroller.standalone.message.McMessageUtils.getPayLoadType(McMessageUtils.java:405)
        at org.mycontroller.standalone.message.McMessageEngine.recordSetTypeData(McMessageEngine.java:958)
        at org.mycontroller.standalone.message.McMessageEngine.execute(McMessageEngine.java:108)
        at org.mycontroller.standalone.message.McMessageEngine.run(McMessageEngine.java:1090)
        at org.mycontroller.standalone.message.McMessageUtils.sendToMcMessageEngine(McMessageUtils.java:662)
        at org.mycontroller.standalone.provider.mysensors.MySensorsProviderBridge.executeRawMessage(MySensorsProviderBridge.java:59)
        at org.mycontroller.standalone.message.McMessageUtils.sendToProviderBridge(McMessageUtils.java:571)
        at org.mycontroller.standalone.message.MessageMonitorThread.processRawMessage(MessageMonitorThread.java:107)
        at org.mycontroller.standalone.message.MessageMonitorThread.run(MessageMonitorThread.java:182)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by jkandasa** [comment]
@nagurao Thanks to reporting this. fix available on the snapshot version
