### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by shajek** [mycontroller-org/mycontroller#467]
Hi
i have Mycontroller 1.3.0 and 1.4.0 snapshot,too but i have this error:
```
2018-09-11 21:57:15,175 ERROR [MQTT Call: mycontroller_rQzD3] [org.mycontroller.standalone.gateway.mqtt.MqttListener:205] Exception, 
java.lang.IllegalArgumentException: No enum constant org.mycontroller.standalone.message.McMessageUtils.MESSAGE_TYPE.1
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at org.mycontroller.standalone.message.McMessageUtils$MESSAGE_TYPE.valueOf(McMessageUtils.java:61)
	at org.mycontroller.standalone.provider.mycontroller.MessageParserMyController.getMessage(MessageParserMyController.java:52)
	at org.mycontroller.standalone.provider.mycontroller.MessageParserMyController.getMessage(MessageParserMyController.java:35)
	at org.mycontroller.standalone.gateway.mqtt.MqttListener.messageArrived(MQTTDriver.java:187)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:499)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:402)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:206)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:299)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
I have  ESP8266 mqtt gateway on mosquitto broker. It is fully working with HomeAssistant. But when i try manage nodes with Mycontroller i have only that error (multiple times).  I add gateway correctly but no nodes, and status since dont update (i think because that error). Can you help me ? Thanks
PS: i use Java 9 (normally working with another java apps that i use), system is CentOS

**Comment by jkandasa** [comment]
@shajek can you post your hardware library details? Are you using MySensors library?
Also, can you post your gateway settings in MyController page?

**Comment by shajek** [comment]
Hi, i look at it over time, and i make huge mistake, i choose MyController gateway, not MySensors. I change it and all is allright now. Thank you
